add queries and update
Mucyosoda/vet_clinic_database pull request #2
Opened 2022-02-16 17:35 UTC by Mucyosoda

vet_clinic DATABASE

>Database vet_clinic has been created with one table, and a table with 6 columns (id, name, date_of_birth, escape_attemps, neutered, weight_kg, species) and inserted rows and Update rows.

2022-02-16 18:03 UTC, ZeenatLawal requested changes

2022-02-16 18:03 UTC, ZeenatLawal commented on data.sql
> +INSERT INTO animals (name, date_of_birth, weight_kg, neutered, escape_attemps) VALUES ('Devimon', date '2017-05-12', 11, true, 5);
- [ ] Kindly remove the `DATE` text written before the date_of_birth entries, the datatype has already been declared in the creation of the table.

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +ROLLBACK;
- [ ] Verify that the change was made before and after rollback as stated in the requirements. e.g
```sql
BEGIN;
UPDATE animals SET species = 'unspecified';
SELECT species from animals; -- verify that change was made
ROLLBACK;
SELECT species from animals; -- verify that change was undone
```

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +COMMIT;
- [ ] Verify that the change was made before and after the commit is made as stated in the requirements. e.g
```sql
BEGIN;
UPDATE animals SET species = 'digimon' WHERE name LIKE '%mon'; 
UPDATE animals SET species = 'pokemon' WHERE species IS NULL; 

SELECT species from animals; -- verify that change was made
COMMIT;
SELECT species from animals; -- verify that change persists after commit
```

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +ROLLBACK;
- [ ] Verify that the change was made before and after the rollback is made as stated in the requirements. e.g
```sql
BEGIN;
DELETE * FROM animals;
SELECT COUNT(*) FROM ANIMALS;

ROLLBACK;
SELECT COUNT(*) FROM ANIMALS;
```

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +SELECT name, escape_attemps FROM animals ORDER BY escape_attemps DESC LIMIT 1;
- [ ] To find who escapes the most, neutered or not neutered animals? Kindly get the avg of the number of escape attempts and group it by neutered. Check example below:
```sql
 SELECT neutered, AVG(escape_attempts) FROM animals GROUP BY neutered;
```

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +SELECT Max(weight_kg) FROM animals WHERE species = 'pokemon';
- [ ] To find the minimum and maximum weight of each type of animal, it'll be good to get the data with one statement as shown below.
```sql
SELECT species, MIN(weight_kg), MAX(weight_kg) FROM animals GROUP BY species;
```

2022-02-16 18:03 UTC, ZeenatLawal commented on queries.sql
> +SELECT AVG(escape_attemps) FROM animals WHERE (date_of_birth BETWEEN '1990-01-01' AND '2000-01-01') AND (species = 'digimon');
- [ ] To find the average number of escape attempts per animal type of those born between 1990 and 2000, it'll be good to get the data with one statement as shown below.
```sql
SELECT species, AVG(escape_attempts) FROM animals GROUP BY species
   WHERE  date_of_birth >= '1990/01/01' AND date_of_birth <= '2000/31/12';
```

2022-02-17 06:39 UTC, descholar-ceo approved these changes
Hi @Mucyosoda , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 07:44 UTC, merged